# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37f8229a70120d781571c02cce5ff6f940cdd3054c7684a54b43a90b7a1bb3ef5804fb1d617ec67cb98d35801313daf5f1b2aebf366729164b71e3533c654a80

test:
  secret_key_base: f0da8e68356d9653ee2ba4c8e10acd23a71f0383cd80a2653f51391118a3a45d8f4c78e9e9e89b51cf978e2b5dc82ec6dc787894c12ca4a46d6408c9feedf69f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
